name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        environment: [staging, production]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Deploy to ${{ matrix.environment }}
        env:
          API_KEY: ${{ secrets.API_KEY }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          echo "Deploying to ${{ matrix.environment }} environment"
          echo "Using API Key: $API_KEY"
          echo "Using Database Password: $DB_PASSWORD"
          # Command to deploy the application, e.g., npm run deploy
          # Assuming deploy command uses API_KEY and DB_PASSWORD as environment variables
          npm run deploy -- --env ${{ matrix.environment }}
    environment: ${{ matrix.environment }}
